export const strings = {
  appTitle: 'PLO Pot Trainer',
  home: {
    settings: '設定',
    today: '今日',
    questions: '問',
    accuracy: '正答率',
    streak: '連続正解',
    startQuiz: '最大レイズ額クイズ',
    chips: 'チップ',
    sim: '実戦',
    triple: '3倍',

    stats: '統計',
    learn: 'ルール学習',
    comingSoon: '準備中',
    noStats: 'まだ記録がありません',
  },
  quiz: {
    nextAction: '次のアクション',
    table: 'ディーラー視点のテーブル',
    hero: 'HERO',
    dealerButton: 'D',
    askPotNow: 'Pot?',
    askRaiseTo: 'いくらまでレイズできる？（合計額）',
    askAddChips: '今いくら出せる？（追加額）',
    hintOwn: 'ヒント: 自分がすでに出した分を足し忘れています',
    hintDouble: 'ヒント: コール額を 2 倍し忘れています',
    hintAfterCall: 'ヒント: コール後のポットで計算しています',
    hintTrail: 'ヒント: トレイル（残りポット）を足し忘れています',
    hintBlind: 'ヒント: ブラインド分ずれています',
    askChipCount: '最小枚数は何枚？',
    askChipTotal: 'このチップの合計は？',
    askTriple: '3倍は？',

    submitSeats: '決定',
    next: '次へ',
    correct: '正解',
    incorrect: '不正解',
    yourAnswer: 'あなた',
    correctAnswer: '正解',
    steps: {
      totalPot: '今のポット P',
      maxAdd: '最大追加',
      raiseTo: 'raise to',
    },
    prevPot: '前ポット',
    total: '合計',
    unknownMode: '不明なモードです',
    missingSession: '結果が見つかりません',
    resultTitle: '結果',
    retry: 'もう一度',
    home: 'ホームへ',
    actions: {
      ante: 'アンティ',
      post: 'ポスト',
      straddle: 'ストラドル',
      fold: 'フォールド',
      check: 'チェック',
      call: 'コール',
      bet: 'ベット',
      raise: 'レイズ to',
    },
  },
  settings: {
    title: '設定',
    back: '戻る',
    rate: 'レート (SB/BB)',
    custom: 'カスタム',
    sb: 'SB',
    bb: 'BB',
    ante: 'アンティ',
    anteNone: 'なし',
    anteBb: 'BB アンティ',
    anteAll: '全員アンティ',
    anteAmount: 'アンティ額',
    straddle: 'ストラドル出題',
    straddleNone: 'なし',
    straddleSingle: 'シングル',
    straddleDouble: 'ダブルまで',
    levels: '出題レベル',
    levelsMin: '下限',
    levelsMax: '上限',
    questionCount: '問題数',
    infinite: '無限',
    timeLimit: '制限時間',
    timeNone: 'なし',
    seconds: '秒',
    chipDenoms: 'チップ額面',
    chipJp: '日本式',
    chipUs: 'US式',
    soundVibe: '効果音・バイブ',
    sound: '効果音',
    vibe: 'バイブ',
    on: 'オン',
    off: 'オフ',
    resetStats: '統計リセット',
    resetConfirm: '統計をすべて消しますか？',
    resetYes: 'リセットする',
    resetNo: 'やめる',
  },
  stats: {
    title: '統計',
    back: '戻る',
    total: '累計問題数',
    accuracy: '正答率',
    averageTime: '平均解答時間',
    byLevel: 'レベル別',
    last14: '直近 14 日',
    bestStreak: '最高連続正解',
    currentStreak: '現在の連続正解',
    weak: '苦手カテゴリ Top3',
    empty: 'まだセッションがありません',
    exportCsv: 'CSV を書き出す',
    level: 'Lv',
    correct: '正答',
    avg: '平均',
  },
  learn: {
    title: 'ルール学習',
    back: '戻る',
    formula: '公式',
    identity: '暗算用ショートカット',
    stepsTitle: 'ディーラー向け 3 ステップ',
    step1: '今テーブルにある全額を数える（前ポット ＋ 全員の今ラウンド投入額）→ P',
    step2: 'コール額を 2 倍して足す → P + 2 × toCall ＝ その人が今出す最大チップ量',
    step3: 'すでに出している自分の分を足す → アナウンスする "raise to" の数字',
    note: '自分が未投入なら 2 と 3 は同じ数字になる。プリフロップの BB / SB / ストラドルだけが 3 を必要とする。',
    example: 'インタラクティブな例題（ヒーロー BB）',
    raiseTo: 'UTG のレイズ to',
    callers: 'コーラー人数',
    result: '最大レイズ額',
  },
  persist: {
    corrupt: '保存データが壊れていたため、初期化しました。',
    schema: '保存データの形式が古い（または不正）だったため、初期化しました。',
    dismiss: '閉じる',
  },
  common: {
    back: '戻る',
    seconds: '秒',
  },
} as const;
